version: "3"

services:
  emily-connectfourapitemplate-mdy08y:

    image: emily-connectfourapitemplate-mdy08y
    container_name: emily-connectfourapitemplate-mdy08y

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-connectfourapitemplate-mdy08y-network

networks:
  emily-connectfourapitemplate-mdy08y-network:
    driver: bridge
    name: emily-connectfourapitemplate-mdy08y-network