version: "3"

services:
  emily-connectfourapitemplate-b6l3dr:

    image: emily-connectfourapitemplate-b6l3dr
    container_name: emily-connectfourapitemplate-b6l3dr

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-connectfourapitemplate-b6l3dr-network

networks:
  emily-connectfourapitemplate-b6l3dr-network:
    driver: bridge
    name: emily-connectfourapitemplate-b6l3dr-network